services:
  - type: web
    name: xsite-capital
    env: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /contact
        destination: /contact.html
      - type: rewrite
        source: /faq
        destination: /faq.html
      - type: rewrite
        source: /team
        destination: /team.html
      - type: rewrite
        source: /assets
        destination: /assets.html
      - type: rewrite
        source: /retirewise
        destination: /retirewise.html
      - type: rewrite
        source: /save35know
        destination: /save35know.html
      - type: rewrite
        source: /ira
        destination: /ira.html
      - type: rewrite
        source: /webinars
        destination: /webinars.html
      - type: rewrite
        source: /money-week
        destination: /money-week/index.html
      - type: rewrite
        source: /julius
        destination: /julius.html
      - type: rewrite
        source: /leslie
        destination: /leslie.html
      - type: rewrite
        source: /tenny
        destination: /tenny.html
